<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="DataSet\MemberWiseReport.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MemberWiseReport.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DataSet\MemberWiseReport.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>MemberWiseReport.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>